configuration: Release

environment:
  app_version: 0.2.$(APPVEYOR_BUILD_NUMBER)

before_build:
  - nuget restore
  
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: $(app_version)
  assembly_file_version: $(app_version)
  assembly_informational_version: $(app_version)

build:
  verbosity: minimal

after_build:
  - ps: powershell .\AfterBuild.ps1

artifacts:
  - path: IForgot\bin\$(configuration)
    name: iforgot

deploy:
  release: v$(app_version)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: GitHub
  auth_token:
    secure: YtUWDe0QCqAklOs3NV/wTu6z06m3OycUM7TW7B6WLQ/LE4csuwL/LzHLNSgB/7w/ # your encrypted token from GitHub
  artifact: /.*\.zip/
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only