//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IForgot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IForgot.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space: manually take screenshot
        ///Del: reset the configuration.
        /// </summary>
        internal static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IForgot - Made by Duco Winterwerp in 2015 - ducode.org.
        /// </summary>
        internal static string CreditsApp {
            get {
                return ResourceManager.GetString("CreditsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon by RaphaelJS (raphaeljs.com).
        /// </summary>
        internal static string CreditsIcon {
            get {
                return ResourceManager.GetString("CreditsIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} old screenshots..
        /// </summary>
        internal static string DeleteOldScreenshots {
            get {
                return ResourceManager.GetString("DeleteOldScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many days should the screenshots be saved?.
        /// </summary>
        internal static string HowManyDays {
            get {
                return ResourceManager.GetString("HowManyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New screenshot taken at {0}: {1}.
        /// </summary>
        internal static string NewScreenshotTaken {
            get {
                return ResourceManager.GetString("NewScreenshotTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the screenshot interval (in seconds):.
        /// </summary>
        internal static string ProvideInterval {
            get {
                return ResourceManager.GetString("ProvideInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the path to where the screenshots should be stored:.
        /// </summary>
        internal static string ProvidePath {
            get {
                return ResourceManager.GetString("ProvidePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file located at: {0}.
        /// </summary>
        internal static string SettingsFileAt {
            get {
                return ResourceManager.GetString("SettingsFileAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings.json file is corrupt. Please delete it..
        /// </summary>
        internal static string SettingsFileCorrupt {
            get {
                return ResourceManager.GetString("SettingsFileCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.json.
        /// </summary>
        internal static string SettingsFileName {
            get {
                return ResourceManager.GetString("SettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new screenshot will be shot in 3 seconds.
        /// </summary>
        internal static string ShootScreenshotIn3Seconds {
            get {
                return ResourceManager.GetString("ShootScreenshotIn3Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong: {0}.
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
    }
}
